baseURL = "https://blog.izassan.net"
languageCode = "ja-jp"
title = "izassan's blog"
copyright = "2021 izassan"

theme = "m10c"


[params]
    author = "izassan"
    description = "現在開発中"
    avatar = "/img/sns_avator.jpg"
    menu_item_separator = " - "
    [[params.social]]
        icon = "github"
        name = "Izassan's Github"
        url = "https://github.com/izassan"
        weight = 100
    [[params.social]]
        icon = "twitter"
        name = "Izassan's Twitter"
        url = "https://twitter.com/izassan_718"
        weight = 110

[menu]
    [[menu.main]]
        identifier = "home"
        name = "Home"
        url = "/"
        weight = 100
    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
        weight = 110
    [[menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags"
        weight = 120
    [[menu.main]]
        identifier = "contact"
        name = "Contact"
        url = "/contact"
        weight = 130
